<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>ed41be28-a049-4fbb-bce8-9742f3791dc3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FoodOrderingSystem.Application\FoodOrderingSystem.Application.csproj" />
    <ProjectReference Include="..\FoodOrderingSystem.Domain\FoodOrderingSystem.Domain.csproj" />
    <ProjectReference Include="..\FoodOrderingSystem.Infrastructure\FoodOrderingSystem.Infrastructure.csproj" />
  </ItemGroup>

</Project>
