<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\FoodOrderingSystem.Domain\FoodOrderingSystem.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Abstractions\Repositories\" />
    <Folder Include="Common\CustomErrors\" />
    <Folder Include="Restaurants\" />
  </ItemGroup>
</Project>
