<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\FoodOrderingSystem.Domain\FoodOrderingSystem.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Common\CustomErrors\" />
    <Folder Include="Restaurants\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Scrutor" />
  </ItemGroup>
</Project>
