// <auto-generated />
using System;
using FoodOrderingSystem.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodOrderingSystem.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("FoodOrdering")
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodOrderingSystem.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "FoodOrdering");

                    b.HasData(
                        new
                        {
                            Id = new Guid("beed0937-74ed-411e-bbe3-843019837c15"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("4eace38b-28b5-4414-8afb-66648ff47fa5"),
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("FoodOrderingSystem.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "FoodOrdering");
                });

            modelBuilder.Entity("FoodOrderingSystem.Domain.Entities.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MenuItems", "FoodOrdering");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7b9d0fd-9cfd-4f6a-9b9a-4f3d1c8b3d2a"),
                            IsAvailable = true,
                            Name = "Margherita Pizza",
                            Price = 12.99m,
                            RestaurantId = new Guid("2d9d6c23-1f2a-4b26-8cf4-8f8d2407c9a1")
                        },
                        new
                        {
                            Id = new Guid("2a6f0c1f-0a6e-4d0e-9c91-2f5d6a4d94fb"),
                            IsAvailable = true,
                            Name = "Pepperoni Pizza",
                            Price = 14.49m,
                            RestaurantId = new Guid("2d9d6c23-1f2a-4b26-8cf4-8f8d2407c9a1")
                        },
                        new
                        {
                            Id = new Guid("d2f5c4d8-5c7c-4f6c-bf2a-2b4d8a9c8f10"),
                            IsAvailable = true,
                            Name = "Garlic Knots",
                            Price = 5.99m,
                            RestaurantId = new Guid("2d9d6c23-1f2a-4b26-8cf4-8f8d2407c9a1")
                        },
                        new
                        {
                            Id = new Guid("4d1a3e2b-6df1-4e48-9c58-0e6f0d8c0db1"),
                            IsAvailable = true,
                            Name = "California Roll",
                            Price = 9.25m,
                            RestaurantId = new Guid("7e3b9c6a-8f1d-4d2a-b5d7-1b728d1a4f3c")
                        },
                        new
                        {
                            Id = new Guid("9a4a44c5-1a9f-4d16-8bda-7e4f0c9d3d6e"),
                            IsAvailable = true,
                            Name = "Salmon Nigiri (6 pcs)",
                            Price = 13.50m,
                            RestaurantId = new Guid("7e3b9c6a-8f1d-4d2a-b5d7-1b728d1a4f3c")
                        },
                        new
                        {
                            Id = new Guid("f0f0b9d2-3b4b-4e7c-8b9a-5b2d0c1a7e4f"),
                            IsAvailable = true,
                            Name = "Miso Soup",
                            Price = 3.75m,
                            RestaurantId = new Guid("7e3b9c6a-8f1d-4d2a-b5d7-1b728d1a4f3c")
                        },
                        new
                        {
                            Id = new Guid("6b2c8a6e-6a80-4a6a-9c9e-b2c35d7d9c12"),
                            IsAvailable = true,
                            Name = "Carnitas Tacos (3)",
                            Price = 10.99m,
                            RestaurantId = new Guid("c4b0f9c8-0b12-4e5a-a754-8f1f1e2c0d7b")
                        },
                        new
                        {
                            Id = new Guid("1e7d5d3a-0b6c-4e0c-9a9b-c3d2e1f0a9b8"),
                            IsAvailable = true,
                            Name = "Chicken Quesadilla",
                            Price = 11.49m,
                            RestaurantId = new Guid("c4b0f9c8-0b12-4e5a-a754-8f1f1e2c0d7b")
                        },
                        new
                        {
                            Id = new Guid("3c9d2a1f-7b8e-4d2a-9c6f-2a1e7b8c9d0e"),
                            IsAvailable = false,
                            Name = "Chips & Salsa",
                            Price = 4.50m,
                            RestaurantId = new Guid("c4b0f9c8-0b12-4e5a-a754-8f1f1e2c0d7b")
                        },
                        new
                        {
                            Id = new Guid("b3c9a1d2-0e4f-4a2b-9b8c-7d6e5f4a3b2c"),
                            IsAvailable = true,
                            Name = "Chicken Tikka Masala",
                            Price = 15.99m,
                            RestaurantId = new Guid("a19f0a6c-3a2b-4f4a-9c4b-2b2c3b1a9f8e")
                        },
                        new
                        {
                            Id = new Guid("7d6c5b4a-3f2e-4d1c-9b8a-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Name = "Chana Masala",
                            Price = 12.49m,
                            RestaurantId = new Guid("a19f0a6c-3a2b-4f4a-9c4b-2b2c3b1a9f8e")
                        },
                        new
                        {
                            Id = new Guid("0a1b2c3d-4e5f-4a6b-9c8d-7e6f5a4b3c2d"),
                            IsAvailable = true,
                            Name = "Garlic Naan",
                            Price = 3.25m,
                            RestaurantId = new Guid("a19f0a6c-3a2b-4f4a-9c4b-2b2c3b1a9f8e")
                        },
                        new
                        {
                            Id = new Guid("c8d7e6f5-4a3b-4c2d-9e1f-0a9b8c7d6e5f"),
                            IsAvailable = true,
                            Name = "Classic Cheeseburger",
                            Price = 13.99m,
                            RestaurantId = new Guid("f6a2d3b1-5c7e-4a3d-9f3a-0c7b2a1d4e6f")
                        },
                        new
                        {
                            Id = new Guid("5f4e3d2c-1b0a-4c9d-8e7f-6a5b4c3d2e1f"),
                            IsAvailable = true,
                            Name = "Crispy Fries",
                            Price = 4.99m,
                            RestaurantId = new Guid("f6a2d3b1-5c7e-4a3d-9f3a-0c7b2a1d4e6f")
                        },
                        new
                        {
                            Id = new Guid("9f8e7d6c-5b4a-4c3d-9e2f-1a0b2c3d4e5f"),
                            IsAvailable = true,
                            Name = "Chocolate Milkshake",
                            Price = 6.49m,
                            RestaurantId = new Guid("f6a2d3b1-5c7e-4a3d-9f3a-0c7b2a1d4e6f")
                        });
                });

            modelBuilder.Entity("FoodOrderingSystem.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders", "FoodOrdering");
                });

            modelBuilder.Entity("FoodOrderingSystem.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", "FoodOrdering");
                });

            modelBuilder.Entity("FoodOrderingSystem.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "FoodOrdering");
                });

            modelBuilder.Entity("FoodOrderingSystem.Domain.Entities.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants", "FoodOrdering");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2d9d6c23-1f2a-4b26-8cf4-8f8d2407c9a1"),
                            City = "New York",
                            IsOpen = true,
                            Name = "Pizza Palace"
                        },
                        new
                        {
                            Id = new Guid("7e3b9c6a-8f1d-4d2a-b5d7-1b728d1a4f3c"),
                            City = "Seattle",
                            IsOpen = true,
                            Name = "Sushi Spot"
                        },
                        new
                        {
                            Id = new Guid("c4b0f9c8-0b12-4e5a-a754-8f1f1e2c0d7b"),
                            City = "Austin",
                            IsOpen = false,
                            Name = "Taco Town"
                        },
                        new
                        {
                            Id = new Guid("a19f0a6c-3a2b-4f4a-9c4b-2b2c3b1a9f8e"),
                            City = "Chicago",
                            IsOpen = true,
                            Name = "Curry Corner"
                        },
                        new
                        {
                            Id = new Guid("f6a2d3b1-5c7e-4a3d-9f3a-0c7b2a1d4e6f"),
                            City = "Denver",
                            IsOpen = true,
                            Name = "Burger Barn"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "FoodOrdering");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "FoodOrdering");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "FoodOrdering");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "FoodOrdering");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "FoodOrdering");
                });

            modelBuilder.Entity("FoodOrderingSystem.Domain.Entities.MenuItem", b =>
                {
                    b.HasOne("FoodOrderingSystem.Domain.Entities.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodOrderingSystem.Domain.Entities.Order", b =>
                {
                    b.HasOne("FoodOrderingSystem.Domain.Entities.ApplicationUser", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FoodOrderingSystem.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("FoodOrderingSystem.Domain.Entities.MenuItem", "MenuItem")
                        .WithOne()
                        .HasForeignKey("FoodOrderingSystem.Domain.Entities.OrderItem", "MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrderingSystem.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FoodOrderingSystem.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("FoodOrderingSystem.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("FoodOrderingSystem.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FoodOrderingSystem.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FoodOrderingSystem.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("FoodOrderingSystem.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrderingSystem.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FoodOrderingSystem.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodOrderingSystem.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
